### ISSUE TITLE
Country codes missing for some countries

### ISSUE THREAD

**Issue by stopyransky** [Omaroid/Covid-19-API#4]
Particularly South Korea heavily impacts the usefullness of the dataset.
List of ISO Codes : https://www.nationsonline.org/oneworld/country_code_list.htm

**Comment by Omaroid** [comment]
Hello, 

Thanks for reporting that issue! I've corrected the refresh to return the good country codes. This may be due to the [2019 Novel Coronavirus (nCoV) Data Repository, provided by JHU CCSE](https://github.com/CSSEGISandData/COVID-19) who have changed some country names. But it's ok now. I'm gonna close this issue !
